### ISSUE TITLE
Cannot Install on Linux, Missing Requirements.txt

### ISSUE THREAD

**Issue by DrewCording** [drov0/python-imagesearch#41]
When attempting to install on Linux I get the following error and am not able to install: 

```
root@localhost:~# python3 -m pip install python-imagesearch --no-cache-dir
Collecting python-imagesearch
  Downloading https://files.pythonhosted.org/packages/0d/45/95e2adbdbcbc0281a2ba1014c1acf278cb7a63f203853f11f261d058dfd2/python-imagesearch-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3i3k34y0/python-imagesearch/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3i3k34y0/python-imagesearch/
root@localhost:~#
```

**Comment by DrewCording** [comment]
Resolved by running

`python3 -m pip install -U pip`

Closed
