### ISSUE TITLE
SystemError: tile cannot extend outside image

### ISSUE THREAD

**Issue by kraftydevil** [drov0/python-imagesearch#7]
First I call imagesearch, which returns coordinates of 2082 478. Everything good there 👍.

Next, I call imagesearcharea using 2060, 460, 400, 400, which based on the first search returning (2082, 478) and size of the image (156, 151) - it should be just the right position and plenty of area.

Instead, I get a `tile cannot extend outside image` SystemError.

Here's the error and code:

```
$ python3 my_example.py 
position :  2082 478
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageFile.py", line 488, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my_example.py", line 10, in <module>
    pos = imagesearcharea("github.png", 2060, 460, 400, 400)
  File "/Users/Username/Projects/Python/python-imagesearch/imagesearch.py", line 47, in imagesearcharea
    im = region_grabber(region=(x1, y1, x2, y2))
  File "/Users/Username/Projects/Python/python-imagesearch/imagesearch.py", line 24, in region_grabber
    return pyautogui.screenshot(region=(x1,y1,width,height))
  File "/usr/local/lib/python3.7/site-packages/pyscreeze/__init__.py", line 375, in _screenshot_osx
    im.save(tmpFilename)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 896, in _save
    [("zip", (0, 0)+im.size, 0, rawmode)])
  File "/usr/local/lib/python3.7/site-packages/PIL/ImageFile.py", line 496, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image
```

my_example.py
```
from imagesearch import *

# search entire screen
pos = imagesearch("github.png")
if pos[0] != -1:
    print("position : ", pos[0], pos[1])
    pyautogui.moveTo(pos[0], pos[1])
else:
    print("image not found")

# search region
pos = imagesearcharea("github.png", 2060, 460, 400, 400)
if pos[0] != -1:
    print("position : ", pos[0], pos[1])
    pyautogui.moveTo(pos[0], pos[1])
else:
    print("image not found")
```

**Comment by drov0** [comment]
Hey sorry for coming back after so long.

I hope you solved your issue, if not your problem comes from the way you use imagesearcharea, 

It's not  imagesearcharea(image, x,y and then you define the size of the search area it's 

It's  imagesearcharea(image, x1,y1,x2,y2) where x1 x2 y1 y2 are the four coordinates of the search area. 

If you want to use it that way you just need to add 400 to each coordinates : 

```
from imagesearch import *
# search entire screen
pos = imagesearch("./github.PNG")
if pos[0] != -1:
    print("position : ", pos[0], pos[1])
    pyautogui.moveTo(pos[0], pos[1])
else:
    print("image not found")

# search region
pos = imagesearcharea("github.PNG", 2060, 460, 2460, 860)
if pos[0] != -1:
    print("position : ", pos[0], pos[1])
    pyautogui.moveTo(pos[0], pos[1])
else:
    print("image not found")
```

**Comment by kraftydevil** [comment]
I should have known!

and no worries - I do appreciate you getting back to me regardless of the time. This was a back burner thing until I had an answer so now I'm a go 👍
